module.exports = {
    screen :'',
    time : 0,
    BASE_URL: 'http://139.59.76.223/kundali_expert/api/',
    firebaseToken:'',
    helpline_number:'',
    ASTRO_API_BASE_URL: 'http://139.59.76.223/kundali_expert/astrology_api/global_api',

    ASTRO_APIS_URL: 'https://json.astrologyapi.com/v1/',
    ASTRO_APIS_PACKAGE: 'Premium ',
    ASTRO_APIS_USERID: '609418',
    ASTRO_APIS_API_KEY: '3f44385e5c9a4a5febc2e9ea7872bacf',

    YOUTUBE_API : 'AIzaSyCkk0Mc6Hha2LUn3NHubv0LLSiumoPVhWs',
    response:'',

    loginmobile:'',
    loginOTP:'',

    opentok_api_key:'46593922',

    isSavedKundli:'0',
    savedKundliDetails:{},
    glLanguage:'en',
    glChartStyle:'north',
    gldate:'',
    glmonth:'',
    glyear:'',
    glhour:'',
    glminute:'',
    gllat:17.2323232,
    gllong:83.232332,
    glzone:'5.5',
    glgender:'male',

    home :'home',
    Signin :'Signin',
    guid:'',    
    user_id:'',
    walletAmount:0,
    headerTitle:'',
    consultType:'',
    deviceIp:'',
    deviceManuf:'',
    deviceCarrier:'',

    event_details:{},
    
    videoDetails:'',
    prodDetails:'',
    catDetails:'',
    all_settings:'',
    userDetails:{},
    addressId:'',


    expId:'',
    expbio:'',

    signupName:'',
    signupEmail:'',
    signupMobile:'',
    signupCountryCode:'',
    signupDob:'',
    signupTob:'',
    signupPob:'',
    signupGender:'',
    signupReferCode:'',
    signupOtp:'',
    signupVerifyRefer:'',
    signupApplyRefer:'',
};